language: ruby
cache: bundler
rvm:
  - 2.2.0
install:
  - bundle install
  - yarn install

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source
  local-dir: _site/
  target-branch: master
  committer-from-gh: true

script:
  - ./script/cibuild.sh

branches:
  only:
    - source

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
