language: ruby
cache: bundler
rvm:
  - 2.2.0
install:
  - bundle install

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source
  local-dir: _site/
  target-branch: master

script:
  - if [ -d "_site" ]; then rm -r _site; fi
  - bundle exec jekyll build

branches:
  only:
    - source
