# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
owner: Jerry Chen
title: jerryjrchen
email: jerry@jerryjrchen.com
description: > # this means to ignore newlines until "baseurl:"
  Jerry Chen's website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jerryjrchen.com" # the base hostname & protocol for your site
github_username:  jerryjrchen
linkedin_username: jerryjrchen
resume: https://www.dropbox.com/s/kgnbj14qclvjjxe/Jerry-Chen-Resume-R.pdf?dl=0

sass:
  load_paths:
    - _scss
  style: compressed

include:
  - .nojekyll # Otherwise, GH pages scraps node_modules

exclude: # Need to keep node_modules
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
permalink: pretty

# Theme setting
theme: jekyll-whiteglass
plugins:
  #- jekyll-archives
  #- jekyll-paginate
  #- jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5 # TODO: pagination is broken

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
