# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jerryjrchen
email: jerry.c@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Jerry Chen's website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jerryjrchen.com" # the base hostname & protocol for your site
github_username:  cjerry
linkedin_username: jerryjrchen
google_analytics: UA-64859905-1

sass:
  load_paths:
    - _sass
    # Needed for bootstrap-material
    - bower_components/bootstrap-sass/assets/stylesheets

# Build settings
markdown: kramdown
